### ISSUE TITLE
InflateException in CodeEditor

### ISSUE THREAD

**Issue by RandunuK** [Rosemoe/sora-editor#153]
I've tried to run the sample app with main branch (11d9416), 0.10.2, 0.10.1, 0.10.0, 0.9.3 and got following error.

Unable to start activity ComponentInfo{io.github.rosemoe.sora.app/io.github.rosemoe.sora.app.MainActivity}: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class io.github.rosemoe.sora.widget.CodeEditor

Android device info:
- OS : 7.0
- Devise : Samsung Galaxy S6

complete log

```
2022-02-27 17:53:03.220 1372-1372/io.github.rosemoe.sora.app E/CrashHandler: Crash at 1645964580267(timestamp) in thread named 'main'
    Local date and time:Feb 27, 2022 5:53:00 PM
    SUPPORTED_64_BIT_ABIS=[arm64-v8a]
    versionCode=37
    CODENAME=REL
    BOARD=universal7420
    BOOTLOADER=G920IDVU4FRD1
    IS_TRANSLATION_ASSISTANT_ENABLED=false
    TYPE=user
    BASE_OS=
    ID=NRD90M
    RELEASE=7.0
    SEM_PLATFORM_INT=80000
    TIME=1523257623000
    BRAND=samsung
    TAG=Build
    HARDWARE=samsungexynos7420
    SERIAL=1215fcba70721e05
    SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
    CPU_ABI=arm64-v8a
    SDK=24
    IS_DEBUGGABLE=false
    RADIO=G920IDVU4FRCA
    ALL_CODENAMES=[REL]
    MANUFACTURER=samsung
    IS_EMULATOR=false
    RESOURCES_SDK_INT=24
    SEM_INT=2402
    INCREMENTAL=G920IDVU4FRD1
    SUPPORTED_32_BIT_ABIS=[armeabi-v7a, armeabi]
    SECURITY_INDEX=1
    SDK_INT=24
    TAGS=release-keys
    CPU_ABI2=
    IS_SYSTEM_SECURE=false
    SECURITY_PATCH=2018-03-01
    UNKNOWN=unknown
    PERMISSIONS_REVIEW_REQUIRED=false
    USER=dpi
    FINGERPRINT=samsung/zerofltedv/zeroflte:7.0/NRD90M/G920IDVU4FRD1:user/release-keys
    ACTIVE_CODENAMES=[]
    PREVIEW_SDK_INT=0
    HOST=SWDG4715
    versionName=0.10.2
    PRODUCT=zerofltedv
    DISPLAY=NRD90M.G920IDVU4FRD1
    MODEL=SM-G920I
    DEVICE=zeroflte
    IS_SECURE=false
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.rosemoe.sora.app/io.github.rosemoe.sora.app.MainActivity}: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class io.github.rosemoe.sora.widget.CodeEditor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class io.github.rosemoe.sora.widget.CodeEditor
     Caused by: android.view.InflateException: Binary XML file line #90: Error inflating class io.github.rosemoe.sora.widget.CodeEditor
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at io.github.rosemoe.sora.app.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:70)
        at io.github.rosemoe.sora.app.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:64)
        at io.github.rosemoe.sora.app.MainActivity.onCreate(MainActivity.kt:69)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.jav
```

**Comment by Rosemoe** [comment]
It looks strange. Is there any more stacktrace?
The stacktrace you sent does not include editor widget calls...

**Comment by Rosemoe** [comment]
Would you mind adding try-catch for the method initialize() in CodeEditor.java and dumping the exception?
If you could not, I'll have time to do that next Saturday.

**Comment by RandunuK** [comment]
i'll do it now

**Comment by Rosemoe** [comment]
> i'll do it now

Thanks a lot!

**Comment by RandunuK** [comment]
![image](https://user-images.githubusercontent.com/7280865/155889111-c475248f-4007-4798-957e-5bfa3978a4ee.png)

I've put try catch block like above. but nothing hit that debug point. 
Is this the correct way?

**Comment by Rosemoe** [comment]
How about catching Throwable?

**Comment by RandunuK** [comment]
Caused by: java.lang.StackOverflowError: stack size 8MB
[crash.log](https://github.com/Rosemoe/sora-editor/files/8148987/crash.log)

**Comment by RandunuK** [comment]
Now it's working. Thank you.
