### ISSUE TITLE
On copying texts it gives IndexOutOfBoundsException error

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [Rosemoe/sora-editor#158]
In the latest update of AndroidIDE (which is based on Sora editor) on copying texts the editor gives IndexOutOfBoundsException error. 

AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2102J20SI
App version: 2.0-beta (200)

 Stacktrace: 
java.lang.IndexOutOfBoundsException: start 0, end 69, s.length() 63
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
	at java.lang.StringBuilder.append(StringBuilder.java:176)
	at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:494)
	at io.github.rosemoe.sora.text.Content.delete(Content.java:407)
	at io.github.rosemoe.sora.widget.CodeEditor.deleteText(CodeEditor.java:1567)
	at io.github.rosemoe.sora.widget.CodeEditor.cutText(CodeEditor.java:2806)
	at com.itsaky.androidide.views.editor.IDEEditor.performTextAction(IDEEditor.java:857)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow.performTextAction(EditorTextActionWindow.java:242)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow.$r8$lambda$1a97XtgRzFmV8POkyslZz1lSeNs(Unknown Source:0)
	at com.itsaky.androidide.views.editor.EditorTextActionWindow$$ExternalSyntheticLambda4.accept(Unknown Source:4)
	at com.itsaky.androidide.adapters.TextActionItemAdapter.lambda$onBindViewHolder$0$com-itsaky-androidide-adapters-TextActionItemAdapter(TextActionItemAdapter.java:88)
	at com.itsaky.androidide.adapters.TextActionItemAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7509)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28710)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by Premjit-Chowdhury** [comment]
Originally Reported here👇
https://github.com/itsaky/AndroidIDE/issues/126#issue-1172025229

**Comment by Rosemoe** [comment]
Please provide a complete procedure description of how to reproduce so that I can debug.

**Comment by Rosemoe** [comment]
It's likely to have been fixed in #157

**Comment by CodeJoker01** [comment]
Maybe this stacktrace will help you to find the issue ;p

 Stacktrace: 
java.lang.IndexOutOfBoundsException: start 0, end 17, s.length() 12
 at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
 at java.lang.StringBuilder.append(StringBuilder.java:176)
 at io.github.rosemoe.sora.text.Content.deleteInternal(Content.java:494)
 at io.github.rosemoe.sora.text.Content.delete(Content.java:407)
 at io.github.rosemoe.sora.text.UndoManager$InsertAction.undo(UndoManager.java:362)
 at io.github.rosemoe.sora.text.UndoManager.undo(UndoManager.java:113)
 at io.github.rosemoe.sora.text.Content.undo(Content.java:537)
 at io.github.rosemoe.sora.widget.CodeEditor.undo(CodeEditor.java:1998)
 at com.itsaky.androidide.views.editor.CodeEditorView.undo(CodeEditorView.java:248)
 at com.itsaky.androidide.EditorActivity.onOptionsItemSelected(EditorActivity.java:529)
 at android.app.Activity.onMenuItemSelected(Activity.java:4326)
 at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
 at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
 at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
 at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
 at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
 at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
 at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
 at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
 at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
 at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
 at android.view.View.performClick(View.java:8160)
 at android.widget.TextView.performClick(TextView.java:16222)
 at android.view.View.performClickInternal(View.java:8137)
 at android.view.View.access$3700(View.java:888)
 at android.view.View$PerformClick.run(View.java:30236)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:246)
 at android.app.ActivityThread.main(ActivityThread.java:8550)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by CodeJoker01** [comment]
Maybe check the UndoManager class.

**Comment by Rosemoe** [comment]
The bug is now fixed
