### ISSUE TITLE
[Bug] Crash on next search

### ISSUE THREAD

**Issue by MrIkso** [Rosemoe/sora-editor#16]
Logcat:
` Process: com.rose.editor.android, PID: 22360
    java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at io.github.rosemoe.editor.text.ContentLine.checkIndex(ContentLine.java:79)
        at io.github.rosemoe.editor.text.ContentLine.charAt(ContentLine.java:302)
        at android.text.TextUtils.indexOf(TextUtils.java:205)
        at android.text.TextUtils.indexOf(TextUtils.java:171)
        at android.text.TextUtils.indexOf(TextUtils.java:286)
        at android.text.TextUtils.indexOf(TextUtils.java:274)
        at io.github.rosemoe.editor.text.ContentLine.indexOf(ContentLine.java:241)
        at io.github.rosemoe.editor.widget.EditorSearcher.gotoNext(EditorSearcher.java:119)
        at io.github.rosemoe.editor.widget.EditorSearcher.gotoNext(EditorSearcher.java:109)
        at com.rose.editor.android.MainActivity.gotoNext(MainActivity.java:279)
        at com.rose.editor.android.MainActivity.onClick(MainActivity.java:316)
        at android.view.View.performClick(View.java:7870)
        at android.widget.TextView.performClick(TextView.java:14970)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`
It is last source from dev branch. I am planning update handle to adroid edittext style, add cursor blinking and more)).

**Comment by MrIkso** [comment]
https://github.com/tranleduy2000/text_editor/blob/master/app/src/main/java/com/jecelyin/editor/v2/utils/ExtGrep.java
maybe use this algorithm to seacrh text(support regex and more)

**Comment by Rosemoe** [comment]
Ok, thanks. I'll try out that.
It is caused by the migration from StringBuilder to ContentLine.
EditorSearcher.java line 124 should be 'column = 0'

**Comment by Rosemoe** [comment]
Searching is improved in 252e2e3d2d6fb33030a45c8f9d26b8b79ea78513
