### ISSUE TITLE
[Crash]  IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Hakalle** [Rosemoe/sora-editor#169]
```
Build version: 0.2.9 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-07 20:16:34 
Device: Unknown Phh-Treble vanilla 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.tyron.code.language.textmate.BaseIncrementalAnalyzeManager$LockedSpans$ReaderImpl.getSpanAt(BaseIncrementalAnalyzeManager.java:428)
	at io.github.rosemoe.sora.widget.EditorPainter.updateLineDisplayList(EditorPainter.java:395)
	at io.github.rosemoe.sora.widget.HwAcceleratedRenderer.drawLineHardwareAccelerated(HwAcceleratedRenderer.java:127)
	at io.github.rosemoe.sora.widget.EditorPainter.drawRows(EditorPainter.java:1014)
	at io.github.rosemoe.sora.widget.EditorPainter.drawView(EditorPainter.java:464)
	at io.github.rosemoe.sora.widget.EditorPainter.draw(EditorPainter.java:128)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3263)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorView.onDraw(CodeEditorView.java:456)
	at android.view.View.draw(View.java:22704)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22707)
	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4525)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4245)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Rosemoe** [comment]
You've reported this in #167 .
Please turn to CodeAssist to inform tyron to update his BaseIncrementalAnalyzeMangaer with newest editor code of AsyncIncremebtalAnalyzeManager
