### ISSUE TITLE
AbstractMethodError when applying TextMate language

### ISSUE THREAD

**Issue by BlueWhaleYT** [Rosemoe/sora-editor#207]
I was thinking should I point out this error or not and anyways I put it.(because idk if it is the problem of myself or what, but I think it is not.)

```
java.lang.AbstractMethodError: abstract method "io.github.rosemoe.sora.lang.analysis.IncrementalAnalyzeManager$LineTokenizeResult io.github.rosemoe.sora.lang.analysis.IncrementalAnalyzeManager.tokenizeLine(java.lang.CharSequence, java.lang.Object)"
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(AsyncIncrementalAnalyzeManager.java:224)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.-$$Nest$minitialize(Unknown Source:0)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread$1.handleMessage(AsyncIncrementalAnalyzeManager.java:251)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(AsyncIncrementalAnalyzeManager.java:330)

```

This error occurs **when a language of TextMate is applied**.

Here's the code.
```java
try {
  EditorColorScheme editorColorScheme = editor.getColorScheme();
  if (!(editorColorScheme instanceof TextMateColorScheme)) {
    IRawTheme iRawTheme = ThemeReader.readThemeSync("MaterialPalenight.tmTheme",
      activity.getAssets().open("textmate/MaterialPalenight.tmTheme"));
    editorColorScheme = TextMateColorScheme.create(iRawTheme);
    editor.setColorScheme(editorColorScheme);
  }

  Language language = TextMateLanguage.create("java.tmLanguage.json",
    activity.getAssets().open("textmate/java/syntaxes/java.tmLanguage.json"),
    new InputStreamReader(activity.getAssets().open("textmate/java/language-configuration.json")),
    ((TextMateColorScheme) editorColorScheme).getRawTheme());

  editor.setEditorLanguage(language);
} catch (Exception e) {
  e.printStackTrace();
  App.dialog(activity, "Error", e.getMessage(), false);
}

// Extra
try {
  IRawTheme iRawTheme = ThemeReader.readThemeSync("MaterialPalenight.tmTheme", activity.getAssets().open("textmate/MaterialPalenight.tmTheme"));
  TextMateColorScheme colorScheme = TextMateColorScheme.create(iRawTheme);
  editor.setColorScheme(colorScheme);

  Language language = editor.getEditorLanguage();
  if (language instanceof TextMateLanguage) {
    TextMateLanguage textMateLanguage = (TextMateLanguage) language;
    textMateLanguage.updateTheme(iRawTheme);
  }
} catch (Exception e) {
  e.printStackTrace();
}
```

The current version of editor `0.12.0`
language-textmate `0.12.0-1`

Thank you.

**Comment by BlueWhaleYT** [comment]
fixed in 0.13.0.
