### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by itsvks19** [Rosemoe/sora-editor#241]
Crash at 1662214816081(timestamp) in thread named 'main'
Local date and time:3 Sept 2022 7:50:16 pm
BOARD=exynos850
SOC_MANUFACTURER=Samsung
ACTIVE_CODENAMES=[]
CPU_ABI2=
SEM_INT=3101
HOST=21DKGA24
SEM_FIRST_SDK_INT=30
versionName=0.17.0-1662214325207
SUPPORTED_64_BIT_ABIS=[arm64-v8a]
CODENAME=REL
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
RELEASE_OR_CODENAME=12
SDK_INT=31
DISPLAY=SP1A.210812.016.F127GXXU3BVG2
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
FINGERPRINT=samsung/f12ins/f12:12/SP1A.210812.016/F127GXXU3BVG2:user/release-keys
PRODUCT=f12ins
PREVIEW_SDK_FINGERPRINT=REL
ID=SP1A.210812.016
SDK=31
SOC_MODEL=Exynos 850
TYPE=user
SERIAL=unknown
DEVICE=f12
ODM_SKU=unknown
SECURITY_PATCH=2022-06-01
TIME=1658851586000
BASE_OS=
MODEL=SM-F127G
RELEASE=12
MANUFACTURER=samsung
USER=dpi
MEDIA_PERFORMANCE_CLASS=0
versionCode=65
BRAND=samsung
SUPPORTED_32_BIT_ABIS=[armeabi-v7a, armeabi]
HARDWARE=exynos850
IS_DEBUGGABLE=false
BOOTLOADER=F127GXXU3BVG2
RADIO=unknown
PREVIEW_SDK_INT=0
UNKNOWN=unknown
IS_EMULATOR=false
SKU=unknown
SEM_PLATFORM_INT=130100
TAGS=release-keys
INCREMENTAL=F127GXXU3BVG2
java.lang.RuntimeException: Unable to destroy activity {io.github.rosemoe.sora.app/io.github.rosemoe.sora.app.LspTestActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5950)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at io.github.rosemoe.sora.utils.CrashHandler.uncaughtException(CrashHandler.java:89)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference
	at io.github.rosemoe.sora.lsp.editor.LspEditor.dispose(LspEditor.java:198)
	at io.github.rosemoe.sora.lsp.editor.LspEditor.close(LspEditor.java:314)
	at io.github.rosemoe.sora.lsp.editor.LspLanguage.destroy(LspLanguage.java:219)
	at io.github.rosemoe.sora.widget.CodeEditor.release(CodeEditor.java:3725)
	at io.github.rosemoe.sora.app.LspTestActivity.onDestroy(LspTestActivity.kt:223)
	at android.app.Activity.performDestroy(Activity.java:8571)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
	... 13 more
java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference
	at io.github.rosemoe.sora.lsp.editor.LspEditor.dispose(LspEditor.java:198)
	at io.github.rosemoe.sora.lsp.editor.LspEditor.close(LspEditor.java:314)
	at io.github.rosemoe.sora.lsp.editor.LspLanguage.destroy(LspLanguage.java:219)
	at io.github.rosemoe.sora.widget.CodeEditor.release(CodeEditor.java:3725)
	at io.github.rosemoe.sora.app.LspTestActivity.onDestroy(LspTestActivity.kt:223)
	at android.app.Activity.performDestroy(Activity.java:8571)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at io.github.rosemoe.sora.utils.CrashHandler.uncaughtException(CrashHandler.java:89)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)

**Comment by dingyi222666** [comment]
I will fix it in next days.
