### ISSUE TITLE
Bug when pressing Key down {KEY DOWN}

### ISSUE THREAD

**Issue by PgmDz** [Rosemoe/sora-editor#246]
This problem happens when I select Swith language -> Java

public void onChildMoved(DataSnapshot arg0, String arg1) {}
                                                                                                          ^   Bug when pressing Key down

Crash at 1662604132680(timestamp) in thread named 'main'
Local date and time:7 de set de 2022 23:28:52
BOARD=fiji
ALL_CODENAMES=[REL]
ACTIVE_CODENAMES=[]
CPU_ABI2=armeabi
MIN_SUPPORTED_TARGET_SDK_INT=17
HOST=ontimbjlx007
versionName=0.17.1-1662534800001
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[]
CODENAME=REL
CPU_ABI=armeabi-v7a
PERMISSIONS_REVIEW_REQUIRED=false
IS_USERDEBUG=false
SDK_INT=28
DISPLAY=POBS29.288-60-6-1-29
SUPPORTED_ABIS=[armeabi-v7a, armeabi]
FINGERPRINT=motorola/fiji/fiji:9/POBS29.288-60-6-1-29/c6fde:user/release-keys
PRODUCT=fiji
ID=POBS29.288-60-6-1-29
SDK=28
TYPE=user
SERIAL=unknown
IS_CONTAINER=false
IS_ENG=false
DEVICE=fiji
RESOURCES_SDK_INT=28
SECURITY_PATCH=2022-01-01
TIME=1645153803000
BASE_OS=motorola/fiji/fiji:9/POBS29.288-60-6-1-15/66fed:user/release-keys
IS_USER=true
MODEL=moto e6s
RELEASE=9
MANUFACTURER=motorola
USER=xscm
versionCode=66
BRAND=motorola
SUPPORTED_32_BIT_ABIS=[armeabi-v7a, armeabi]
HARDWARE=mt6765
IS_DEBUGGABLE=false
FIRST_SDK_INT=28
BOOTLOADER=fiji-8f1915b-20211104103059-20220218131227
RADIO=unknown
PREVIEW_SDK_INT=0
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
INCREMENTAL=c6fde
java.lang.AbstractMethodError: abstract method "io.github.rosemoe.sora.lang.smartEnter.NewlineHandleResult io.github.rosemoe.sora.lang.smartEnter.NewlineHandler.handleNewline(io.github.rosemoe.sora.text.Content, io.github.rosemoe.sora.text.CharPosition, io.github.rosemoe.sora.lang.styling.Styles, int)"
	at io.github.rosemoe.sora.widget.EditorKeyEventHandler.onKeyDown(EditorKeyEventHandler.java:213)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(CodeEditor.java:3955)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2701)
	at android.view.View.dispatchKeyEvent(View.java:12470)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1902)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1902)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1902)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1902)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1902)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1902)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:429)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3360)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:124)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:142)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3089)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:343)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5215)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5078)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4648)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4614)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4754)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4622)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4811)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4648)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4614)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4622)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4595)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7351)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7320)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7271)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4367)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:916)

**Comment by Rosemoe** [comment]
Rebuild your project fully. This is caused by newly added default method in `NewlineHandler`

**Comment by PgmDz** [comment]
![Screenshot_20220907-234317](https://user-images.githubusercontent.com/107230983/189021948-e77aa76b-a0c2-45ff-9d61-c39f05d3a621.png)

**Comment by Rosemoe** [comment]
Downloaded from GitHub Actions?

**Comment by PgmDz** [comment]
Yes

**Comment by Rosemoe** [comment]
Try to install this one in [newest CI build](https://github.com/Rosemoe/sora-editor/actions/runs/3012840201)

**Comment by PgmDz** [comment]
had the same problem.
