### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Rosemoe/sora-editor#284]
```
java.lang.StringIndexOutOfBoundsException: length=0; index=0
       at java.lang.String.charAt(Native Method)
       at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:275)
       at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:131)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:339)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Rosemoe** [comment]
already fixed by 54f8dd0d33d52865e0e0a17a0a67b9da6ffe758f, and new version will be released soon.
