### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Rosemoe/sora-editor#285]
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.eclipse.tm4e.core.internal.theme.IRawTheme.getName()' on a null object reference
       at io.github.rosemoe.sora.langs.textmate.registry.ThemeRegistry.findThemeByThemeName(ThemeRegistry.java:98)
       at io.github.rosemoe.sora.langs.textmate.registry.ThemeRegistry.loadTheme(ThemeRegistry.java:73)
       at io.github.rosemoe.sora.langs.textmate.registry.ThemeRegistry.loadTheme(ThemeRegistry.java:66)
```

**Comment by Rosemoe** [comment]
Please describe what you were doing/how to reproduce the problem in detail.
This will help us solve the bug earlier.

**Comment by dingyi222666** [comment]
Please describe the bug report in more detail, for example, what code or action was performed that caused the crash, this will help us to solve the bug better.

**Comment by LinXueyuanStdio** [comment]
Hi. I forget to call `loadDefaultThemes` and `loadDefaultLanguages` before calling `editor.setEditorLanguage(language)`

The above error is fixed after I properly init these objects.
