### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when onDraw

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#294]
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: Index -1 out of bounds. length:5158
       at io.github.rosemoe.sora.text.Content.checkIndex(Content.java:947)
       at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:337)
       at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:331)
       at io.github.rosemoe.sora.widget.EditorRenderer.drawRows(EditorRenderer.java:947)
       at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:590)
       at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:191)
       at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4029)
       at android.view.View.draw(View.java:22354)
       at android.view.View.updateDisplayListIfDirty(View.java:21230)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
       at android.view.View.updateDisplayListIfDirty(View.java:21190)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
       at android.view.View.updateDisplayListIfDirty(View.java:21190)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
       at android.view.View.updateDisplayListIfDirty(View.java:21190)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
       at android.view.View.updateDisplayListIfDirty(View.java:21190)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
       at android.view.View.updateDisplayListIfDirty(View.java:21190)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
       at android.view.View.updateDisplayListIfDirty(View.java:21190)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8191)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
       at android.view.Choreographer.doCallbacks(Choreographer.java:878)
       at android.view.Choreographer.doFrame(Choreographer.java:811)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7705)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by kyze8439690** [comment]
Another similar crash

```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: Index 128023 out of bounds. length:126906
       at io.github.rosemoe.sora.text.Content.checkIndex(Content.java:959)
       at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:337)
       at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:331)
       at io.github.rosemoe.sora.widget.EditorRenderer.drawRows(EditorRenderer.java:949)
       at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:592)
       at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:191)
       at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4034)
```

**Comment by Rosemoe** [comment]
> Another similar crash when using library version 0.19.0
> 
> ```
> Fatal Exception: java.lang.StringIndexOutOfBoundsException: Index 128023 out of bounds. length:126906
>        at io.github.rosemoe.sora.text.Content.checkIndex(Content.java:959)
>        at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:337)
>        at io.github.rosemoe.sora.text.CachedIndexer.getCharPosition(CachedIndexer.java:331)
>        at io.github.rosemoe.sora.widget.EditorRenderer.drawRows(EditorRenderer.java:949)
>        at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:592)
>        at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:191)
>        at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4034)
> ```

The same issue as above.
