### ISSUE TITLE
Another IndexOutOfBoundsException

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#307]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at io.github.rosemoe.sora.widget.layout.WordwrapLayout.findRow(WordwrapLayout.java:135)
       at io.github.rosemoe.sora.widget.CodeEditor.setLayoutBusy(CodeEditor.java:2875)
       at io.github.rosemoe.sora.widget.layout.WordwrapLayout.lambda$breakAllLines$0(WordwrapLayout.java:94)
       at androidx.camera.core.impl.LiveDataObservable$$InternalSyntheticLambda$7$a9a5965b87d10334f8c0aba5086ea045ca686aecdae5dcbe3b542da4b10ce063$0.run$bridge(LiveDataObservable.java:84)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:268)
       at android.app.ActivityThread.main(ActivityThread.java:8017)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Comment by kyze8439690** [comment]
androidx.camera.core.impl.LiveDataObservable？
