### ISSUE TITLE
IllegalArgumentException when dispatch touch event

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#362]
```
Fatal Exception: java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 51 is less than minimum 190.
       at kotlin.ranges.RangesKt___RangesKt.coerceIn(RangesKt___RangesKt.java:1413)
       at io.github.rosemoe.sora.widget.layout.BidiLayoutHelper.horizontalIndex(BidiLayoutHelper.java:105)
       at io.github.rosemoe.sora.widget.layout.WordwrapLayout.getCharPositionForLayoutOffset(WordwrapLayout.java:379)
       at io.github.rosemoe.sora.widget.CodeEditor.getPointPosition(CodeEditor.java:2055)
       at io.github.rosemoe.sora.widget.EditorTouchEventHandler$SelectionHandle.applyPosition(EditorTouchEventHandler.java:838)
       at io.github.rosemoe.sora.widget.EditorTouchEventHandler.handleSelectionChange(EditorTouchEventHandler.java:431)
       at io.github.rosemoe.sora.widget.EditorTouchEventHandler.onTouchEvent(EditorTouchEventHandler.java:367)
       at io.github.rosemoe.sora.widget.CodeEditor.onTouchEvent(CodeEditor.java:4219)
       at android.view.View.dispatchTouchEvent(View.java:15533)
       at io.github.rosemoe.sora.widget.CodeEditor.dispatchTouchEvent(CodeEditor.java:4176)
```

**Comment by MohammedKHC0** [comment]
Did this got fixed??
