### ISSUE TITLE
IllegalArgumentException when constructing CodeEditor 

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#363]
```
Caused by java.lang.IllegalArgumentException:
       at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1278)
       at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1166)
       at io.github.rosemoe.sora.widget.layout.AbstractLayout.<clinit>(AbstractLayout.java:47)
       at io.github.rosemoe.sora.widget.CodeEditor.createLayout(CodeEditor.java:1610)
       at io.github.rosemoe.sora.widget.CodeEditor.createLayout(CodeEditor.java:1586)
       at io.github.rosemoe.sora.widget.CodeEditor.setTextSizePx(CodeEditor.java:1243)
       at io.github.rosemoe.sora.widget.CodeEditor.setTextSize(CodeEditor.java:3617)
       at io.github.rosemoe.sora.widget.CodeEditor.initialize(CodeEditor.java:532)
       at io.github.rosemoe.sora.widget.CodeEditor.<init>(CodeEditor.java:342)
       at io.github.rosemoe.sora.widget.CodeEditor.<init>(CodeEditor.java:337)
       at io.github.rosemoe.sora.widget.CodeEditor.<init>(CodeEditor.java:333)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
```

**Comment by Rosemoe** [comment]
It seems to be the same as #320

**Comment by kyze8439690** [comment]
Oh, I am still using 0.20.4, sorry for that.

**Comment by kyze8439690** [comment]
It seems that the bug fix is released in [0.20.0](https://github.com/Rosemoe/sora-editor/releases/tag/0.20.0), but I am still seeing this crash in 0.20.4.

**Comment by Rosemoe** [comment]
The crash log is probably collected from an old version of sora-editor.
Because since 451d3918f31386953f7b962cfd68db91763358db, the executor initialization has been moved from line 47 to line 52. And since 632ddae24eff6862c9eb9602cfc3ab8b1f8480d7, line 54.
![image](https://user-images.githubusercontent.com/28822819/213997599-3f700595-2ca7-41cc-8349-981ae673b030.png)

**Comment by kyze8439690** [comment]
You are right, actual sora editor version is 0.19.0:

```
implementation(platform("io.github.Rosemoe.sora-editor:bom:0.19.0"))
implementation("io.github.Rosemoe.sora-editor:editor")
implementation("io.github.Rosemoe.sora-editor:language-textmate")
```

I should have check my code first, sorry for bothering.
