### ISSUE TITLE
OOM when analyzing content

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#368]
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 36473520 byte allocation with 4337320 free bytes and 4235KB until OOM, target footprint 402653184, growth limit 402653184
       at org.eclipse.tm4e.core.internal.oniguruma.OnigString$MultiByteString.getByteToCharOffsets(OnigString.java:79)
       at org.eclipse.tm4e.core.internal.oniguruma.OnigString$MultiByteString.getCharIndexOfByte(OnigString.java:110)
       at org.eclipse.tm4e.core.internal.oniguruma.OnigNextMatchResult.captureIndicesOfMatch(OnigNextMatchResult.java:43)
       at org.eclipse.tm4e.core.internal.oniguruma.OnigNextMatchResult.<init>(OnigNextMatchResult.java:34)
       at org.eclipse.tm4e.core.internal.oniguruma.OnigScanner.findNextMatchSync(OnigScanner.java:39)
       at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.matchRule(LineTokenizer.java:343)
       at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.matchRuleOrInjections(LineTokenizer.java:356)
       at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:151)
       at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
       at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
       at org.eclipse.tm4e.core.internal.grammar.Grammar._tokenize(Grammar.java:346)
       at org.eclipse.tm4e.core.internal.grammar.Grammar.tokenizeLine2(Grammar.java:274)
       at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:213)
       at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:68)
       at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(AsyncIncrementalAnalyzeManager.java:486)
       at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.-$$Nest$minitialize(AsyncIncrementalAnalyzeManager.java:59)
       at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread$1.handleMessage(AsyncIncrementalAnalyzeManager.java:515)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(AsyncIncrementalAnalyzeManager.java:622)
```

**Comment by Rosemoe** [comment]
This is memory allocation by textmate internal analysis and is possibly caused by too long line.
We recommend not editting text with long lines in the editor. Or you have to disable the tokenization.

**Comment by kyze8439690** [comment]
Is it possible to catch this exception instead of crashing?
