### ISSUE TITLE
StackOverflowError in LineTokenizer (v0.21.0)

### ISSUE THREAD

**Issue by radimitrov** [Rosemoe/sora-editor#396]
``Something in this code causes a StackOverflowError exception in the editor's TextMate line tokenizer.
Code to reproduce in editor:
```csharp
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net;

namespace StackOverflowThrownInSoraEditorLineTokenizer
{
[OnLang("hu")]
public class HungarianHttpStatusCodeErrorDisplayFormatter : IHttpStatusCodeErrorDisplayFormatter
{
public string Format(HttpStatusCode statusCode,string method,string path,Dictionary<string,string> errors)
{
return $"{method} HTTP kérés a {path} végpontra hibát dobott vissza {statusCode}{(int)statusCode} statuszkoddal:\n\t{String.Join("\n",errors.Select(x => $"\t{x.Key} hiba: {x.Value}"))}";
}
}
}
```

Full stack trace: https://pastebin.com/mQkaKitP
Partial stack trace:
```
 java.lang.StackOverflowError: stack size 1035KB
        at java.util.ArrayList$SubList.size(ArrayList.java:1056)
        at java.util.Collections$UnmodifiableCollection.size(Collections.java:1077)
        at com.google.common.collect.Lists$ReverseList.size(Lists.java:868)
        at com.google.common.collect.Lists$ReverseList.reverseIndex(Lists.java:822)
        at com.google.common.collect.Lists$ReverseList.get(Lists.java:863)
        at org.eclipse.tm4e.core.internal.theme.Theme._scopePathMatchesParentScopes(Theme.java:105)
        at org.eclipse.tm4e.core.internal.theme.Theme.lambda$match$1$org-eclipse-tm4e-core-internal-theme-Theme(Theme.java:87)
        at org.eclipse.tm4e.core.internal.theme.Theme$$ExternalSyntheticLambda2.test(Unknown Source:6)
        at org.eclipse.tm4e.core.internal.utils.MoreCollections.findFirstMatching(MoreCollections.java:41)
        at org.eclipse.tm4e.core.internal.theme.Theme.match(Theme.java:86)
        at org.eclipse.tm4e.core.internal.registry.SyncRegistry.themeMatch(SyncRegistry.java:101)
        at org.eclipse.tm4e.core.internal.grammar.AttributedScopeStack._pushAttributed(AttributedScopeStack.java:151)
        at org.eclipse.tm4e.core.internal.grammar.AttributedScopeStack.pushAttributed(AttributedScopeStack.java:133)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:516)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:223)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
E/AndroidRuntime:     at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.handleCaptures(LineTokenizer.java:507)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scanNext(LineTokenizer.java:306)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.scan(LineTokenizer.java:142)
        at org.eclipse.tm4e.core.internal.grammar.LineTokenizer.tokenizeString(LineTokenizer.java:599)

**Comment by dingyi222666** [comment]
We need more details to debug this error. Please specify the TextMate grammar file, Android version and any other relevant info.

**Comment by radimitrov** [comment]
I've only tested on Android 12 and 13. It seems to only happen with the attached grammar file, however it isn't modified so it should work.
[csharp_tmlanguage.zip](https://github.com/Rosemoe/sora-editor/files/10931350/csharp_tmlanguage.zip)

**Comment by radimitrov** [comment]
Any progress on this bug? Or at least a workaround?

**Comment by dingyi222666** [comment]
Sorry for the late reply. I tested your tmLanguage file and sample code on my own fork of sora-editor and did not encounter the issue you mentioned. This is my branch: https://github.com/dingyi222666/sora-editor/tree/main.
