### ISSUE TITLE
How can I fix that error??

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [Rosemoe/sora-editor#398]
### Discussed in https://github.com/Rosemoe/sora-editor/discussions/397

<div type='discussions-op-text'>

<sup>Originally posted by **TechnicalStudioDeveloper** March  4, 2023</sup>
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/joni/Regex;
	at org.eclipse.tm4e.core.internal.oniguruma.OnigRegExp.<init>(OnigRegExp.java:54)
	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.createFoldingExp(TextMateAnalyzer.java:103)
	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.<init>(TextMateAnalyzer.java:93)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.<init>(TextMateLanguage.java:44)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:51)
	at com.ts.code.editor.editor.SoraEditor.SetUpSoraCodeEditor(SoraEditor.java:65)
	at com.ts.code.editor.CodeEditorActivity$5$2.onClick(CodeEditorActivity.java:256)
	at android.view.View.performClick(View.java:7184)
	at android.view.View.performClickInternal(View.java:7157)
	at android.view.View.access$3500(View.java:821)
	at android.view.View$PerformClick.run(View.java:27660)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
Caused by: java.lang.ClassNotFoundException: org.joni.Regex
	... 18 more
</div>

**Comment by Rosemoe** [comment]
Add all dependencies to your project.

**Comment by TechnicalStudioDeveloper** [comment]
which dependency??
