### ISSUE TITLE
NPE when `CodeEditor` calls `Formatter.isRunning()`

### ISSUE THREAD

**Issue by ThatMG393** [Rosemoe/sora-editor#407]
Crashes my app immediately

**Logs**:
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean io.github.rosemoe.sora.lang.format.Formatter.isRunning()' on a null object reference
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at io.github.rosemoe.sora.widget.CodeEditor.isFormatting(CodeEditor.java:3745)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at io.github.rosemoe.sora.widget.EditorRenderer.drawFormatTip(EditorRenderer.java:743)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:703)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:199)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4150)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24406)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23267)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24409)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23267)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23253)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24136)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1540)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.draw(View.java:24409)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at com.android.internal.policy.DecorView.draw(DecorView.java:1513)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.View.updateDisplayListIfDirty(View.java:23267)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
03-31 09:15:47.766 15233/15233 AndroidRuntime_           E  	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.view.Choreographer.doFrame(Choreographer.java:852)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.os.Handler.handleCallback(Handler.java:942)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.os.Handler.dispatchMessage(Handler.java:99)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.os.Looper.loopOnce(Looper.java:226)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.os.Looper.loop(Looper.java:313)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at android.app.ActivityThread.main(ActivityThread.java:8757)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at java.lang.reflect.Method.invoke(Native Method)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
03-31 09:15:47.767 15233/15233 AndroidRuntime_           E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by Rosemoe** [comment]
You've probably created your own language. The Language object should return a non-null value in method getFormatter.
You may use EmptyFormatter if it is not implemented.

**Comment by ThatMG393** [comment]
@Rosemoe I did not create a new language and I also fixed it.

**Comment by ThatMG393** [comment]
@Rosemoe 
It seems like "LspEditor.setEditor(CodeEditor)" doesn't set the editor so when the library calls "LspEditor.getEditor()" it returns null. And I am very very sure that I am using the same `LspEditor` object
