### ISSUE TITLE
SDK 24

### ISSUE THREAD

**Issue by timscriptov** [Rosemoe/sora-editor#532]
Failed to get scroll factor, using default.
                                                                                                    java.lang.NumberFormatException: For input string: "64.0dip"
                                                                                                    	at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
                                                                                                    	at java.lang.Float.parseFloat(Float.java:459)
                                                                                                    	at android.content.res.TypedArray.getFloat(TypedArray.java:406)
                                                                                                    	at io.github.rosemoe.sora.widget.CodeEditor.initialize(CodeEditor.java:535)
                                                                                                    	at io.github.rosemoe.sora.widget.CodeEditor.<init>(CodeEditor.java:364)
                                                                                                    	at io.github.rosemoe.sora.widget.CodeEditor.<init>(CodeEditor.java:359)
                                                                                                    	at io.github.rosemoe.sora.widget.CodeEditor.<init>(CodeEditor.java:355)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                                    	at com.mcal.neweditor.databinding.ActivitySoraeditorBinding.inflate(ActivitySoraeditorBinding.java:103)
                                                                                                    	at com.mcal.neweditor.databinding.ActivitySoraeditorBinding.inflate(ActivitySoraeditorBinding.java:97)
                                                                                                    	at com.mcal.editor.presentation.EditorActivity$1.invoke(EditorActivity.kt:57)
                                                                                                    	at com.mcal.editor.presentation.EditorActivity$1.invoke(EditorActivity.kt:57)
                                                                                                    	at com.mcal.presentation.base.BaseActivity$binding$2.invoke(BaseActivity.kt:30)
                                                                                                    	at com.mcal.presentation.base.BaseActivity$binding$2.invoke(BaseActivity.kt:29)
                                                                                                    	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
                                                                                                    	at com.mcal.presentation.base.BaseActivity.getBinding(BaseActivity.kt:29)
                                                                                                    	at com.mcal.presentation.base.BaseActivity.onCreate(BaseActivity.kt:35)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:6662)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                                    	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
2024-01-12 22:44:45.340  2940-2991  AndroidRuntime          com.mcal.apkeditor.pro               E  FATAL EXCEPTION: AsyncAnalyzer-1
                                                                                                    Process: com.mcal.apkeditor.pro, PID: 2940
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:213)
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:68)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(AsyncIncrementalAnalyzeManager.java:473)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.handleMessage(AsyncIncrementalAnalyzeManager.java:495)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(AsyncIncrementalAnalyzeManager.java:603)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.mcal.apkeditor.pro-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mcal.apkeditor.pro-2/lib/x86_64, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:213) 
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:68) 
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(AsyncIncrementalAnalyzeManager.java:473) 
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.handleMessage(AsyncIncrementalAnalyzeManager.java:495) 
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(AsyncIncrementalAnalyzeManager.java:603)

**Comment by Rosemoe** [comment]
> `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;`

Enable l8 desugaring to settle the problem. Textmate uses some Java APIs that are not in old Android versions. We use l8 desugaring to make them compatible.
