### ISSUE TITLE
Crash due to code editor : java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by m-anshuman2166** [Rosemoe/sora-editor#546]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at io.github.rosemoe.sora.widget.CodeEditor.getPointPositionOnScreen(CodeEditor.java:2210)
       at io.github.rosemoe.sora.widget.EditorTouchEventHandler.onSingleTapUp(EditorTouchEventHandler.java:538)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:758)
       at io.github.rosemoe.sora.widget.CodeEditor.onTouchEvent(CodeEditor.java:4597)
       at android.view.View.dispatchTouchEvent(View.java:14360)
       at io.github.rosemoe.sora.widget.CodeEditor.dispatchTouchEvent(CodeEditor.java:4517)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:540)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4221)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:498)
       at android.view.View.dispatchPointerEvent(View.java:14619)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6188)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5991)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5482)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5539)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5505)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5657)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5513)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5714)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5486)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5539)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5505)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5513)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5486)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8333)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8249)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8210)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8469)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:227)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:207)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8413)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8508)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
       at android.view.Choreographer.doCallbacks(Choreographer.java:796)
       at android.view.Choreographer.doFrame(Choreographer.java:724)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7851)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
# Occurrences Experienced On : 
* Android 11, Moto G(9) Play
* Android 10, Tecno Spark 5 Pro
* Android 11, Redmi Note 8
* Android 11, HOT Play
* Android 11, Galaxy A20s
* Android 11, Galaxy A30s

Crash reports collected through Firebase Crashlytics, on my own device, i'm unable to reproduce the error.

**Comment by Rosemoe** [comment]
The bug is due to a missing check before locating sticky scroll lines. The Y axis value can be out of bounds when the user use the selection handles and finally causes the exception.

It is fixed together in 6ab5a8fd6d2eec56b0bb0610dfadd526eb9284dd, and is released in 0.23.3.
