### ISSUE TITLE
Crash when reuse CodeEditor and Content object

### ISSUE THREAD

**Issue by StarkZhidian** [Rosemoe/sora-editor#561]
Hi, I want to implement open multi code files with the same CodeEditor object  to save memory, But I got a Crash when reuse CodeEditor and Content object：

```
java.lang.IndexOutOfBoundsException: Index: 15, Size: 9
    at java.util.ArrayList.get(ArrayList.java:437)
    at io.github.rosemoe.sora.text.Content.getLine(Content.java:259)
    at io.github.rosemoe.sora.text.Content.getColumnCount(Content.java:282)
    at io.github.rosemoe.sora.widget.layout.LineBreakLayout.getCharLayoutOffset(LineBreakLayout.java:222)
    at io.github.rosemoe.sora.widget.layout.Layout$-CC.$default$getCharLayoutOffset(Layout.java:125)
    at io.github.rosemoe.sora.widget.layout.AbstractLayout.getCharLayoutOffset(AbstractLayout.java:0)
    at io.github.rosemoe.sora.widget.CodeEditor.updateCursorAnchor(CodeEditor.java:1804)
    at io.github.rosemoe.sora.widget.CodeEditor.updateCursor(CodeEditor.java:4271)
    at io.github.rosemoe.sora.widget.EditorInputConnection.finishComposingText(EditorInputConnection.java:546)
    at android.view.inputmethod.BaseInputConnection.closeConnection(BaseInputConnection.java:161)
    at io.github.rosemoe.sora.widget.EditorInputConnection.closeConnection(EditorInputConnection.java:138)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:536)
    at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:223)
    at com.android.internal.view.IInputConnectionWrapper.closeConnection(IInputConnectionWrapper.java:209)
    at android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.deactivate(InputMethodManager.java:828)
    at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1881)
    at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1768)
    at io.github.rosemoe.sora.widget.CodeEditor.setText(CodeEditor.java:3785)
    at io.github.rosemoe.sora.widget.CodeEditor.setText(CodeEditor.java:3717)
```

Does anyone know the reason?

**Comment by Rosemoe** [comment]
Same as #562
