### ISSUE TITLE
Language-Textmate Desugar not work

### ISSUE THREAD

**Issue by STICKnoLOGIC** [Rosemoe/sora-editor#588]
Version: 0.24.2
Android device: Android 9, Vivo v9, aarch64
OpenJDK version: 17

Error Description:
`
FATAL EXCEPTION: AsyncAnalyzer-1
                                                                                                    Process: com.new.example.ide, PID: 31811
                                                                                                    java.lang.NoSuchMethodError: No virtual method toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /system/framework/core-oj.jar)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:250)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:101)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:173)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:101)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:209)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:78)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:173)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:78)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compileCaptures(RuleFactory.java:134)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:98)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:209)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:101)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:173)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:78)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar._tokenize(Grammar.java:282)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.tokenizeLine2(Grammar.java:271)
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:212)
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:67)
2024-05-13 19:08:43.707 31811-31910 AndroidRuntime          ph.sticknologic.com.laraide          E  	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(AsyncIncrementalAnalyzeManager.java:451)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.handleMessage(AsyncIncrementalAnalyzeManager.java:473)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(AsyncIncrementalAnalyzeManager.java:581)
`

What I already done to try to fix it:
of course, Enable desugaring as what it said in documentation,
Restart Android Studio, Build Apk (not running app/Shift + F10),
using cli, "gradlew assembleDebug" / "gradlew clean assembleDebug"
downgrading language-textmate to 0.23.x and 0.22.x

all of the above methods only show that error...

**Comment by STICKnoLOGIC** [comment]
update:
I also use the current snapshot version and same error occurred

**Comment by dingyi222666** [comment]
See #591

**Comment by Raival-e** [comment]
I still get the same error, even in the latest release (v 0.23.4).

**Comment by dingyi222666** [comment]
> I still get the same error, even in the latest release (v 0.23.4).

Use `SNAPSHOT` version.

Because no new version has been released since the merge of this PR.

https://github.com/Rosemoe/sora-editor/pull/410

**Comment by Raival-e** [comment]
Thanks for pointing that out.
