### ISSUE TITLE
OutOfMemoryError exception when opening 365M file

### ISSUE THREAD

**Issue by zhanlan123** [Rosemoe/sora-editor#596]
```bash
version: io.github.Rosemoe.sora-editor:bom:0.22.0

Stack：
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 163304 free bytes and 159KB until OOM, target footprint 402653184, growth limit 402653184; giving up on allocation because <1% of heap free after GC.
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:398)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:103)
	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:66)
	at io.github.rosemoe.sora.text.ContentIO.createFrom(ContentIO.java:55)
	at top.yinlingfeng.xlog.decode.DisplayLogFileActivity.openAssetsFile$lambda$9(DisplayLogFileActivity.kt:204)
	at top.yinlingfeng.xlog.decode.DisplayLogFileActivity.$r8$lambda$8sa9Mf0xiwFhft2UKPmv5oyFJUI(Unknown Source:0)
	at top.yinlingfeng.xlog.decode.DisplayLogFileActivity$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:930)
```

**Comment by Rosemoe** [comment]
Android offers up to 512M vm heap memory and you can not directly open this file in the editor. 
You may externally implement paged editing.
