### ISSUE TITLE
crash in new line by press ok

### ISSUE THREAD

**Issue by nalcwap** [Rosemoe/sora-editor#631]
hi in my device minsdk21 android 5.02 when i write java code and press ok to add new line it crashes with error,its possible fix please?error is

Sketchware Pro v6.4.0-SNAPSHOT-d9cbc47-minApi21 (150)
base.apk size: 116MB (121461894 B)
Locale: pt_PT
SDK version: 22
Brand: asus
Manufacturer: asus
Model: ASUS_Z01QD

```
Sketchware Pro v6.4.0-SNAPSHOT-d9cbc47-minApi21 (150)
base.apk size: 116MB (121461894 B)
Locale: pt_PT
SDK version: 22
Brand: asus
Manufacturer: asus
Model: ASUS_Z01QD

```
java.lang.AbstractMethodError: abstract method "int io.github.rosemoe.sora.lang.Language.getIndentAdvance(io.github.rosemoe.sora.text.ContentReference, int, int, int, int)"
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(CodeEditor.java:1977)
	at io.github.rosemoe.sora.widget.EditorKeyEventHandler.handleEnterKeyEvent(EditorKeyEventHandler.java:568)
	at io.github.rosemoe.sora.widget.EditorKeyEventHandler.handleKeyEvent(EditorKeyEventHandler.java:196)
	at io.github.rosemoe.sora.widget.EditorKeyEventHandler.onKeyDown(EditorKeyEventHandler.java:151)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(CodeEditor.java:4670)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2619)
	at android.view.View.dispatchKeyEvent(View.java:8411)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1519)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1519)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1519)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1519)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1519)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1519)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2361)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1709)
	at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:135)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:88)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2276)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4020)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3982)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3713)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3874)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2236)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1877)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1868)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2213)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

```

**Comment by Rosemoe** [comment]
This is caused by incomplete desugaring during the APK build and will happen on SDK 23-
