### ISSUE TITLE
GrammarRegistry scope name not found

### ISSUE THREAD

**Issue by nullyiming** [Rosemoe/sora-editor#633]
机型:红米
系统:miui13
Android版本:12
IDE:AndroidIDE
我之前也用过AndroidStudio也是闪退
跟着https://project-sora.github.io/sora-editor-docs
写的代码
报错:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sorattt/com.example.sorattt.MainActivity}: java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@859df31 scope name not found
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3957)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8290)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@859df31 scope name not found
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:153)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:146)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:142)
	at com.example.sorattt.MainActivity.onCreate(MainActivity.java:76)
	at android.app.Activity.performCreate(Activity.java:8167)
	at android.app.Activity.performCreate(Activity.java:8134)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	... 12 more
```
![Screenshot_2024-12-04-15-03-50-005-edit_com itsaky androidide](https://github.com/user-attachments/assets/7325f17d-7b8f-4aca-a082-55914763821d)
![Screenshot_2024-12-04-15-04-04-631-edit_com itsaky androidide](https://github.com/user-attachments/assets/df304ce7-16d0-495d-b97d-baf332ad422e)
![Screenshot_2024-12-04-15-04-24-071_com itsaky androidide](https://github.com/user-attachments/assets/b19ea0ce-101f-469f-b143-b875d02c34ba)
![IMG_20241204_150502](https://github.com/user-attachments/assets/688760ca-30e8-4fd5-87f6-5b57374b4292)

**Comment by Rosemoe** [comment]
我似乎并没有从您的代码中发现问题。
您是否可以将 textmate 语法文件附上以便我们调查此问题？

**Comment by nullyiming** [comment]
我之前也用过https://github.com/microsoft/vscode
里面的textmate文件，也是这个错误
下面是文件内容:

gdscript.language-configuration.json:
![Screenshot_2024-12-05-10-16-58-341_com itsaky androidide](https://github.com/user-attachments/assets/30e2b595-2155-4dab-9675-a64e641009a4)



quietlight.json:
![Screenshot_2024-12-05-10-17-06-175_com itsaky androidide](https://github.com/user-attachments/assets/a3297482-d018-4667-823b-f1fb9b60376f)


GDScript.tmLanguage.json:
![Screenshot_2024-12-05-10-15-51-797_com itsaky androidide](https://github.com/user-attachments/assets/02deaa21-d86e-4de2-b99a-edb6a60f0d61)

**Comment by Rosemoe** [comment]
实际测试了一下，并没有预期中的崩溃，但是这个语法确实不受支持。您提供的报错应该是之前遗漏加载语法语句留下的。
此语法文件不受支持的原因在于 tm4e 使用的 joni 不支持下面这段表达式：`(?<!/\s*)(\$\s*|%|\$%\s*)(/\s*)?([a-zA-Z_]\w*)\b(?!\s*/)`: `SyntaxException: invalid pattern in look-behind`
VSCode 用的是 [oniguruma](https://github.com/kkos/oniguruma)，而 [joni](https://github.com/jruby/joni) 是 oniguruma 的 Java 实现，存在一定功能上的差异，而且 joni 也很久没有发版了。
可能需要手动把不受 joni 支持的表达式修改成 joni 支持的表达式。

**Comment by nullyiming** [comment]
我更改为了https://github.com/microsoft/vscode
里面的javatextmate文件
还是这个错误

languages.json:
![Screenshot_2024-12-05-11-02-35-251_com itsaky androidide](https://github.com/user-attachments/assets/74702843-b99e-4c94-8737-df8f3a507d59)

![Screenshot_2024-12-05-11-02-25-740_com itsaky androidide](https://github.com/user-attachments/assets/165e09c0-1abc-4cc3-a801-ee87e91fb2a9)
![Screenshot_2024-12-05-11-02-44-218_com itsaky androidide](https://github.com/user-attachments/assets/e3956632-82f4-4a2e-b69a-a1b22a35f459)

**Comment by Rosemoe** [comment]
vscode 的 java tmbundle 就是我们 demo 一直在用的 bundle

**Comment by nullyiming** [comment]
我知道，因为我就是跟着那个教程来的，
但是当我修改之后还是报错:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sorattt/com.example.sorattt.MainActivity}: java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@859df31 scope name not found
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3957)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8290)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@859df31 scope name not found
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:153)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:146)
	at io.github.rosemoe.sora.langs.textmate.TextMateLanguage.create(TextMateLanguage.java:142)
	at com.example.sorattt.MainActivity.onCreate(MainActivity.java:76)
	at android.app.Activity.performCreate(Activity.java:8167)
	at android.app.Activity.performCreate(Activity.java:8134)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	... 12 more

```

**Comment by Rosemoe** [comment]
可以尝试 clean&rebuild 一下，你看你报错的行号上面根本没有东西

**Comment by nullyiming** [comment]
因为app直接闪退了，我是在系统里一个叫第三方应用异常记录里找到的。
这是我使用try之后拦截的报错:
```
java.lang.IllegalArgumentException: Language with io.github.rosemoe.sora.langs.textmate.registry.GrammarRegistry@859df31 scope name not found
```

**Comment by Rosemoe** [comment]
你的 `languages.json` 存放位置不对，你现在放的位置应该是和 `textmate` 文件夹平级的。

**Comment by nullyiming** [comment]
我现在改正确了，但是直接闪退，没有提示，有时候能看见一下CodeEditor不过不到一秒就闪退了
![Screenshot_2024-12-05-11-41-49-246-edit_com itsaky androidide](https://github.com/user-attachments/assets/e8cd4e30-9aa7-40b1-8032-21957363d5b5)
![Screenshot_2024-12-05-11-41-55-335_com itsaky androidide](https://github.com/user-attachments/assets/7b44b660-2bfb-4762-ba6b-886bcee523aa)

**Comment by Rosemoe** [comment]
最好查看一下 log，我也无法确定问题所在

**Comment by nullyiming** [comment]
我又在AndroidStudio，还是闪退
这是logcat:
```
2024-12-05 13:28:20.755  1388-1629  HiDATA_HiNetwork        system_server                        E  monitor handleActivityChange curPkgName is com.huawei.android.launcher curUid is 10060 lastPkgName is :com.yiming.soratest
2024-12-05 13:28:20.763  1388-1629  HiDATA_HiNetwork        system_server                        E  onAppEnd enter packageName is com.yiming.soratest mode is:0
2024-12-05 13:28:20.766  1388-1629  HiDATA_HiNetwork        system_server                        E  contain db file packageName: com.yiming.soratest iscanacce:-1
2024-12-05 13:28:27.601 13564-13564 yiming.sorates          com.yiming.soratest                  I  Late-enabling -Xcheck:jni
2024-12-05 13:28:27.658 13564-13564 yiming.sorates          com.yiming.soratest                  I  Reinit property: dalvik.vm.checkjni= false
2024-12-05 13:28:27.788 13564-13591 HwApiCacheMangerEx      com.yiming.soratest                  I  apicache path=/storage/emulated/0 state=mounted key=com.yiming.soratest#10116#256
2024-12-05 13:28:27.788 13564-13591 HwApiCacheMangerEx      com.yiming.soratest                  I  apicache path=/storage/0403-0201 state=mounted key=com.yiming.soratest#10116#256
2024-12-05 13:28:27.795 13564-13591 HwApiCacheMangerEx      com.yiming.soratest                  I  apicache path=/storage/emulated/0 state=mounted key=com.yiming.soratest#10116#0
2024-12-05 13:28:27.795 13564-13591 HwApiCacheMangerEx      com.yiming.soratest                  I  apicache path=/storage/0403-0201 state=mounted key=com.yiming.soratest#10116#0
2024-12-05 13:28:28.050  1388-1404  AwareLog                system_server                        E  RMS.AwareIntelligentRecg: delete pkg:com.yiming.soratest userid:0 from iAware.db
2024-12-05 13:28:28.703 13564-13564 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::Init
2024-12-05 13:28:28.703 13564-13564 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.703 13564-13564 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::StartWatch
2024-12-05 13:28:28.703 13564-13564 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/com.yiming.soratest
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::Run
2024-12-05 13:28:28.704 13564-13564 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13648 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::Reading
2024-12-05 13:28:28.704 13564-13648 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13648 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::CheckNotifyEvent
2024-12-05 13:28:28.704 13564-13648 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.704 13564-13648 yiming.sorates          com.yiming.soratest                  I  QarthPatchMonintor::CheckNotifyEvent before read
2024-12-05 13:28:28.704 13564-13648 yiming.sorates          com.yiming.soratest                  I  
2024-12-05 13:28:28.712 13564-13591 AwareBitmapCacher       com.yiming.soratest                  I  init processName:com.yiming.soratest pid=13564 uid=10116
2024-12-05 13:28:28.717 13564-13649 AwareLog                com.yiming.soratest                  E  AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@f6a44a9
2024-12-05 13:28:28.718 13564-13649 AwareLog                com.yiming.soratest                  E  AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@4e0ea2e
2024-12-05 13:28:28.720 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden field Landroid/os/Trace;->TRACE_TAG_APP:J (light greylist, reflection)
2024-12-05 13:28:28.720 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (light greylist, reflection)
2024-12-05 13:28:28.745 13564-13591 MemoryLeak...torManager com.yiming.soratest                  E  MemoryLeakMonitor.jar is not exist!
2024-12-05 13:28:28.927 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
2024-12-05 13:28:28.927 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
2024-12-05 13:28:28.927 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
2024-12-05 13:28:28.927 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2024-12-05 13:28:28.956 13564-13564 HwApsImpl               com.yiming.soratest                  I  APS: new HwApsImpl created
2024-12-05 13:28:28.972 13564-13564 HwPhoneWindow           com.yiming.soratest                  I  updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
2024-12-05 13:28:28.974 13564-13564 HwPhoneWindow           com.yiming.soratest                  I  updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=false, mIsFloating=false
2024-12-05 13:28:29.035 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2024-12-05 13:28:29.038 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2024-12-05 13:28:29.197 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden method Landroid/graphics/Paint;->getTextRunAdvances([CIIIIZ[FI)F (light greylist, linking)
2024-12-05 13:28:29.249 13564-13564 OverScroll...timization com.yiming.soratest                  I  start init SmartSlideOverScroller and get the overscroller config
2024-12-05 13:28:29.250 13564-13564 OverScroll...timization com.yiming.soratest                  I  get the overscroller config
2024-12-05 13:28:29.254 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.255 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.259 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.259 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.356 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.357 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.358 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.359 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.379 13564-13564 AwareAppScheduleManager com.yiming.soratest                  I  post cache drawable res id to aware, resId = 2131165412, packagename = com.yiming.soratest, cost time = 13734769
2024-12-05 13:28:29.426 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.426 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.428 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.428 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.486 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.486 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.487 13564-13564 FLTAG_FM                com.yiming.soratest                  I  loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.487 13564-13564 FLTAG_SFM               com.yiming.soratest                  I  getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2024-12-05 13:28:29.793 13564-13564 yiming.sorates          com.yiming.soratest                  W  Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
2024-12-05 13:28:30.292 13564-13730 yiming.sorates          com.yiming.soratest                  W  Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
2024-12-05 13:28:30.292 13564-13730 yiming.sorates          com.yiming.soratest                  E  [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2024-12-05 13:28:30.297 13564-13730 AndroidRuntime          com.yiming.soratest                  E  FATAL EXCEPTION: AsyncAnalyzer-1
                                                                                                    Process: com.yiming.soratest, PID: 13564
                                                                                                    java.lang.NoSuchMethodError: No virtual method toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /system/framework/core-oj.jar)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:250)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:101)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda3.apply(Unknown Source:8)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:209)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:78)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda3.apply(Unknown Source:8)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:173)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:78)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda3.apply(Unknown Source:8)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:173)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:101)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda3.apply(Unknown Source:8)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(RuleFactory.java:209)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(RuleFactory.java:78)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory$$ExternalSyntheticLambda3.apply(Unknown Source:8)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Grammar.java:208)
                                                                                                    	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(RuleFactory.java:53)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar._tokenize(Grammar.java:282)
                                                                                                    	at org.eclipse.tm4e.core.internal.grammar.Grammar.tokenizeLine2(Grammar.java:271)
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:211)
                                                                                                    	at io.github.rosemoe.sora.langs.textmate.TextMateAnalyzer.tokenizeLine(TextMateAnalyzer.java:66)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.initialize(AsyncIncrementalAnalyzeManager.java:450)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.handleMessage(AsyncIncrementalAnalyzeManager.java:472)
                                                                                                    	at io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread.run(AsyncIncrementalAnalyzeManager.java:580)
2024-12-05 13:28:30.322 13564-13730 Process                 com.yiming.soratest                  I  Sending signal. PID: 13564 SIG: 9
2024-12-05 13:28:30.353  1388-2133  WindowManager           system_server                        E  win=Window{68ae8d4 u0 Splash Screen com.yiming.soratest EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
2024-12-05 13:28:30.363  1861-13696 HwNaturalBase           com.huawei.HwOPServer                E  [AppDataClearReceiver]: clearDataByOwner ignore: Found null values with the given ownerPkgName is[com.yiming.soratest].
2024-12-05 13:28:30.363  1861-13696 HwNaturalBase           com.huawei.HwOPServer                E  [AppDataClearReceiver]: AppDataClearBroadcastReceiver: clearPrimaryKeyData  pkg is com.yiming.soratest data failed, userId is 0

```

**Comment by Rosemoe** [comment]
此问题已在更新的版本中解决，你可以尝试 v0.23.5

**Comment by nullyiming** [comment]
可以了，谢谢大佬，不过怎么不会自动提示，autoCompleteEnabled设置为true了，只有输入之后才会自动提示比如private这些，只有高亮，需要输入一次之后才能自动提示，有办法设置一下吗

**Comment by Rosemoe** [comment]
可以使用 `TextMateLanguage#setCompleterKeywords` 为补全设置内置关键字，其他的只能靠从文本中获取。

**Comment by nullyiming** [comment]
好的，我刚才又试了试Androidide结果显示找不到0.23.5这个版本的库

**Comment by Rosemoe** [comment]
> 好的，我刚才又试了试Androidide结果显示找不到0.23.5这个版本的库

也许还没同步进仓库，可以过一会儿再试，也可以继续用 SNAPSHOT 区别不大

**Comment by nullyiming** [comment]
感谢大佬
